analytics: {}
color:
  brandColors:
    - '#FFFFFF'
    - '#470B01'
    - '#9B3202'
    - '#D24700'
    - '#FFB500'
  brandStrength: 0.331081
  lightness: 1
  rhythmicContrast: 0
  saturation: 0.287162
cta: {}
layout_spectrum: 0.63928
name: The reVue Boney M.Show
opengraph: {}
purpose: []
typography_spectrum: 0.61182
