analytics: {}
color:
  brandColors:
    - '#FFFFFF'
    - '#470B01'
    - '#9B3202'
    - '#D24700'
    - '#FFB500'
  brandStrength: 0.496621
  lightness: 0.9375
  rhythmicContrast: 0.719594
  saturation: 0.10304
cta: {}
layout_spectrum: 0.63928
name: The reVue Boney M.Show
opengraph: {}
purpose: []
typography_spectrum: 0.61182
