name: The reVue Boney M.Show
favicon: null
layout_spectrum: 0.82394
typography_spectrum: 0.61182
title: The reVue Boney M.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefc'
    - '#181609'
    - '#b31f00'
    - '#b7ba9d'
    - '#86581c'
  brandStrength: 0.25
  lightness: 0.9375
  saturation: 0.3125
  rhythmicContrast: 1
purpose: []
