name: The reVue Boney M.Show
favicon: null
layout_spectrum: 1
typography_spectrum: 0.61182
title: The reVue BM
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.11733293207362294
  lightness: 0.9607270213309675
  saturation: 0.34011076972819865
  rhythmicContrast: 0.9727266884874552
purpose: []
